### PR TITLE
Code Revision

### PR DESCRIPTION
**Pull request by sturgill**
[As discussed](https://github.com/zevarito/mixpanel/pull/46), here's a quick refactor making use of Mixpanel::Tracker.  I've tested it to work in JRuby, 1.8.7, REE, 1.9.2, and 1.9.3.  The version number would just need to be updated to reflect the change (also, your [recent change](https://github.com/zevarito/mixpanel/commit/65d4c43b3341712f9410f22939b89eee40eee978) isn't part of this pull request).

### CODE REVIEW

**Comment by zevarito** [comment]
Hi @sturgill, thanks for submitting your work.

Before merge your changes I need to ask you to update your method definitions following the coding style already used in the gem. You are defining methods without include () around parameters, we only use that style if the method doesn't receive any paramaters. Thanks again.

**Comment by sturgill** [comment]
Done.

**Comment by zevarito** [comment]
@sturgill Merge is giving me some conflicts, I will fix those Tomorrow. Thanks.

**Comment by zevarito** [comment]
Hi @sturgill, if you are able to resolve the conflicts by merging master in your work, that will be really helpful to delivery a new version of the gem faster. I am with lot of client work this week and I am not sure where I will have time to make this. Thanks again.

**Comment by sturgill** [comment]
Done and pushed.  All that you should need to do is add a line to the CHANGELOG and update the version in mixpanel.gemspec.

**Comment by zevarito** [comment]
Done and pushed new version of the Gem. Thanks.

**Pull request merged**
