### PR TITLE
Track events that happen on the client side which does not hit the server

### PR DESCRIPTION
**Pull request by vantran**
Hi, I made some changes to the mixpanel gem to allow people to wrap javascript around the events that will be tracked. It's useful to track users interactions that do not hit the server.

Example: A user click on a registration form that's a lightbox (server doesn't get hit, but this event should still be tracked)

```
@mixpanel.append_event_with_js('Click beta request',
      lambda {|code| "$('#beta-request').click(function() { #{code} });" },
      {:from_page => "Home page"})
```

### CODE REVIEW

**Comment by eric** [comment]
Any reason why you wouldn't just create your own block in your `<head>` for this?

```
<script type='text/javascript'>jQuery(document).ready(function() { <%= yield :javascript_on_load %> });</script>
```

and then

```
content_for :javascript_on_load, <<-EOF
  $('#div_id').click(function() { mpq.push(['track', { some: 'property' }]) });
EOF
```

I have trouble seeing how this code change improves the amount of code that needs to be written.

**Comment by vantran** [comment]
Because I don't want to spread my tracking code out over all my view files. Especially when Mixpanel says they'll still track events sent to them even if the events are deleted from their site's dashboard. It would not be easy to see all the events I'm currently tracking. Some events don't have a view, so it's not possible to do it all from a shared view file.

What I do currently is I put all my tracking code in application_controller.rb like this:

```
def mixpanel_tracking
  @mixpanel = Mixpanel.new("API_KEY", request.env, true)
  located_at = params[:controller] + "/" + params[:action]

  # Home page
  case located_at
  when "home/index"
    @mixpanel.append_event('Load home page')
    @mixpanel.append_event_with_js('Click beta request',
      lambda {|code| "$('#home-join').click(function() { #{code} });" },
      {:from_page => "Home page"})

  # About page
  when "abouts/show"
    @mixpanel.append_event('Load about page')
  # More tracking code, etc...
  else
  end
end
```

Perhaps this can be improved by putting it in a module. I'll be doing that next...

**Comment by zevarito** [comment]
Hi @vantran,

I am not sure about this implementation, the example that you give us makes controller's know about view details, which in my opinion is not a good idea, views are a totally separated layer and controllers shouldn't know nothing about that.

I know that sometimes the views gets too dirty cause of things like this, but in my opinion I prefer to have a good separation between layers even if it has the cost of have dirty views.

I am sure there are several workarounds for this if you don't like @eric's approach, which in my opinion, I would have done the same to solve the problem.

As I said before, that is my opinion, I would like to hear more pros and cons as in every pull request that mixpanel gem had.

**Comment by vantran** [comment]
I understand. No biggie, to each his own. I've spread my tracking code out before and greatly disliked not knowing what I'm tracking, so I'll stick to this approach.

**Pull request closed without merging**
