### PR TITLE
Fix for large ajax responses in rails

### PR DESCRIPTION
**Pull request by tinomen**
I added an issue on you repo about an error I've encountered regarding large ajax responses. This commit has the patch I've put in place on our production app. I tired to make a spec to duplicate the error but I can't generate a string big enough to actually cause the error in rspec or irb. The old posts I could find about this error were from old rails forum posts.

My fix involves replacing the gsub! call with insert(0,str). This may be not offer any real performance improvement, especially on small strings, but it has removed the error from my application. The test I added is somewhat worthless since it doesn't actually reproduce the error but I thought it was worth having a non trivial response document.

### CODE REVIEW

**Comment by zevarito** [comment]
cool, I will check it out, thanks!

**Comment by zevarito** [comment]
merged.

If you are planning to do more commits, I should add you as a contributor/maintainer.

**Comment by tinomen** [comment]
I have one more change to allow setting of distinct_id property when initializing the mixpanel class. We have found this setting makes a world of difference when users access the site from different IPs. I'll submit the change when I've had a chance to test it in our production env.

**Comment by zevarito** [comment]
@tinomen,

sounds good! looking forward to see those changes.

**Pull request merged**
