### PR TITLE
Mixpanel logger configuration

### PR DESCRIPTION
**Pull request by nfedyashev**
Hi!

I was thinking that it maybe useful to have a way to enable logs for Mixpanel notifications.
I'm using this gem in a production project, and we have quite complex Mixpanel notifications logic.

Having these calls in log helps a lot! I hope that this would be useful for someone else.

### CODE REVIEW

**Comment by zevarito** [comment]
Hi @nfedyashev,

I think this feature is really good, can you please update the Readme file explaining how this can be used before merge?

Thanks.

**Comment by nfedyashev** [comment]
I was thinking about that but I guess we don't even need to change README, look:

For any usual user there is no need to change anything in configuration - Mixpanel logger just picks default Rails logger.
Rails log all `DEBUG` level messages in every environment except production. That is exactly what we're trying to achieve.

It covers wast majority of cases but if anyone needs something _really_ complex they will look at the source anyways :) Implementation is pretty simple.

What do you think, Alvaro?

**Comment by zevarito** [comment]
Well,

I think is good to know that it will be using your logger, and also to know that you can change that. It is a feature after all.

**Comment by andywatts** [comment]
+1 for merging this as is.

**Comment by zevarito** [comment]
Hello, I am reading this on vacations, bad inet though, I'll try to do it
asap.

Alvaro

**Comment by zevarito** [comment]
@nf

**Comment by zevarito** [comment]
@nfedyashev Seems like I cannot merge your commits, did you delete your own repo?

**Comment by nfedyashev** [comment]
@zevarito I did.

**Comment by zevarito** [comment]
Can you push it back so I can merge your commits?

On Thu, Jan 10, 2013 at 3:00 PM, Nikita Fedyashev
notifications@github.comwrote:

> @zevarito https://github.com/zevarito I did.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zevarito/mixpanel/pull/18#issuecomment-12106864.

## 

Alvaro

**Pull request closed without merging**
