### PR TITLE
Allow to specify "test" when sending events using the HTTP interface

### PR DESCRIPTION
**Pull request by romanbsd**
https://mixpanel.com/docs/api-documentation/http-specification-insert-data

### CODE REVIEW

**Comment by zevarito** [comment]
Hey @romanbsd,

this is cool, can you update documentation as well ?

Thanks.

**Comment by romanbsd** [comment]
Done

**Comment by zevarito** [comment]
Merged thanks.

Do you need to pull the gem or can you use the feature building a local gem from github/master?

I am asking this because I today i've pushed a new version, and there are other fixes about to finish so all they can create a new version together.

Best.

**Comment by romanbsd** [comment]
I'll wait until it's in the released gem..

**Pull request merged**
