### PR TITLE
Add track_charge and reset_charges to Mixpanel::Person

### PR DESCRIPTION
**Pull request by nottombrown**
Also add vendor/bundle to the .gitignore as many people store their bundles there instead of in .bundle.

Thanks for the awesome library!

### CODE REVIEW

**Comment by michiels** [comment]
Oh I didn't see this awesome pull request :smile:. Your code looks much cleaner.

What do you think of naming the method `track_charge` since this is inconsistent with the current gem and with the Mixpanel API. I don't mind that much, but is there any way of keeping this consistent?

I propose renaming the internel `append` method to `append_to_queue` or something.

**Comment by nottombrown** [comment]
Maybe we could call it `append_transaction` instead of `track_charge`? Renaming `append` everywhere seems like a rather large change.

**Comment by zevarito** [comment]
I think we can merge this as it is to introduce the feature with a minor version change, then we can rename `append` method and release a mayor version letting know users that their applications will break.

Let me know what do you think.

**Comment by nottombrown** [comment]
I'm on board with that. Sounds good to me.

**Comment by michiels** [comment]
Cool! I would also be really happy with that!

Op 17 jan. 2013 om 16:10 heeft Alvaro Gil notifications@github.com het volgende geschreven:

**Comment by Facens** [comment]
Hi, does this method work with append? And in case, how? #70 seems to, but I can't find any reference here.

**Pull request merged**
