### PR TITLE
Add support for mixpanel.people.identify

### PR DESCRIPTION
**Pull request by AhmedBelal**
https://github.com/zevarito/mixpanel/issues/50

### CODE REVIEW

**Comment by zevarito** [comment]
@AhmedBelal Hey!

Sorry has been busy last days.

Does justify the presence of the old method `append_identify` after adding `append_people_identify` ?

Should that be deprecated?

Also, please update the README documenting how and why use this method you are adding.

Thanks!

**Comment by AhmedBelal** [comment]
The old method, `append_identify`, should not be deprecated since (1) it has not been deprecated in the Mixpanel API, (2) it is appropriate method to use if you're not using Mixpanel People.

**Comment by zevarito** [comment]
Yeah, well not sure if it should belong to Person class.

I'll will merge and push a new version of the gem this afternoon, I'll let you know. Thanks.

**Comment by AhmedBelal** [comment]
Yes, `append_identity` should be moved to the Event class.

**Comment by zevarito** [comment]
Pushed 3.0.2 version of the gem.

**Comment by AhmedBelal** [comment]
Great, thanks!

**Pull request merged**
